language: python
python: 3.8
branches: master

install:
    - pip install -e .[docs]

script: true

before_deploy: # Build documentation
    - pdoc --html --force --output-dir docs nfb_studio

deploy: # Deploy documentation to Github in the gh_pages branch
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    keep_history: true
    local_dir: docs/nfb_studio
    on:
        branch: master